import { UserButton } from "@clerk/nextjs";
import Head from "next/head";
import { Fragment } from "react";
import Counter from "~/components/Counter";
import PlusConter from "~/components/PlusCounter";
import { api } from "~/utils/api";

const defaultCounters = [
  {
    name: "Quran",
    category: 1,
  },
  {
    name: "Fasting",
    category: 2,
  },
  {
    name: "Tahadjjud",
    category: 4,
  },
  {
    name: "Salawat",
    category: 5
  }
]

export default function Home() {
  

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>				<UserButton afterSignOutUrl="/"/></header>
      <main className="grid w-full sm:w-1/2 grid-cols-2 gap-4 p-4 ">
        {defaultCounters.map((i) => 
        <Fragment key={`index-${i.name}`}>
          <Counter title={i.name} onUpdate={(hey, i)=> console.log(hey, i)}/>
        </Fragment>
        )}
        <div className="w-full h-full flex justify-center max-w-xs items-center">
          <PlusConter />
          </div>
      </main>
    </>
  );
}
